///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EMSTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckEmployeePage recording.
    /// </summary>
    [TestModule("651865f2-35a5-4ddb-a479-b7046ad00ca4", ModuleType.Recording, 1)]
    public partial class CheckEmployeePage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EMSTestRepository repository.
        /// </summary>
        public static EMSTestRepository repo = EMSTestRepository.Instance;

        static CheckEmployeePage instance = new CheckEmployeePage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckEmployeePage()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckEmployeePage Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.Employee' at 43;19.", repo.HomePageEMSWeb.EmployeeInfo, new RecordItemIndex(0));
            repo.HomePageEMSWeb.Employee.Click("43;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Employee List') on item 'HomePageEMSWeb.EmployeeList'.", repo.HomePageEMSWeb.EmployeeListInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.HomePageEMSWeb.EmployeeListInfo, "InnerText", "Employee List");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
