///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EMSTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteEmployee recording.
    /// </summary>
    [TestModule("b05853ee-699e-4246-8c2d-ad28648b2668", ModuleType.Recording, 1)]
    public partial class DeleteEmployee : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EMSTestRepository repository.
        /// </summary>
        public static EMSTestRepository repo = EMSTestRepository.Instance;

        static DeleteEmployee instance = new DeleteEmployee();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteEmployee()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteEmployee Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.Employee' at 38;27.", repo.HomePageEMSWeb.EmployeeInfo, new RecordItemIndex(0));
            repo.HomePageEMSWeb.Employee.Click("38;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.CRUDOperations.BtnDelete' at 8;19.", repo.HomePageEMSWeb.CRUDOperations.BtnDeleteInfo, new RecordItemIndex(1));
            repo.HomePageEMSWeb.CRUDOperations.BtnDelete.Click("8;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.CRUDOperations.BtnDelete1' at 31;14.", repo.HomePageEMSWeb.CRUDOperations.BtnDelete1Info, new RecordItemIndex(2));
            repo.HomePageEMSWeb.CRUDOperations.BtnDelete1.Click("31;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Employee deleted successfully') on item 'HomePageEMSWeb.CRUDOperations.EmployeeDeletedSuccessfully'.", repo.HomePageEMSWeb.CRUDOperations.EmployeeDeletedSuccessfullyInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.HomePageEMSWeb.CRUDOperations.EmployeeDeletedSuccessfullyInfo, "InnerText", "Employee deleted successfully");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
