///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EMSTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditEmployee recording.
    /// </summary>
    [TestModule("3b593539-22c4-4832-9e16-5754b8c31ff7", ModuleType.Recording, 1)]
    public partial class EditEmployee : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EMSTestRepository repository.
        /// </summary>
        public static EMSTestRepository repo = EMSTestRepository.Instance;

        static EditEmployee instance = new EditEmployee();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditEmployee()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditEmployee Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.Employee' at 52;19.", repo.HomePageEMSWeb.EmployeeInfo, new RecordItemIndex(0));
            repo.HomePageEMSWeb.Employee.Click("52;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.CRUDOperations.BtnEdit' at 48;17.", repo.HomePageEMSWeb.CRUDOperations.BtnEditInfo, new RecordItemIndex(1));
            repo.HomePageEMSWeb.CRUDOperations.BtnEdit.Click("48;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.Name' at 85;19.", repo.HomePageEMSWeb.NameInfo, new RecordItemIndex(2));
            repo.HomePageEMSWeb.Name.Click("85;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'EDITED' with focus on 'HomePageEMSWeb.Name'.", repo.HomePageEMSWeb.NameInfo, new RecordItemIndex(3));
            repo.HomePageEMSWeb.Name.PressKeys("EDITED");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.Position' at 89;20.", repo.HomePageEMSWeb.PositionInfo, new RecordItemIndex(4));
            repo.HomePageEMSWeb.Position.Click("89;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'EDITED' with focus on 'HomePageEMSWeb.Position'.", repo.HomePageEMSWeb.PositionInfo, new RecordItemIndex(5));
            repo.HomePageEMSWeb.Position.PressKeys("EDITED");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.Salary' at 108;18.", repo.HomePageEMSWeb.SalaryInfo, new RecordItemIndex(6));
            repo.HomePageEMSWeb.Salary.Click("108;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '000' with focus on 'HomePageEMSWeb.Salary'.", repo.HomePageEMSWeb.SalaryInfo, new RecordItemIndex(7));
            repo.HomePageEMSWeb.Salary.PressKeys("000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomePageEMSWeb.CRUDOperations.BtnUpdate' at 101;14.", repo.HomePageEMSWeb.CRUDOperations.BtnUpdateInfo, new RecordItemIndex(8));
            repo.HomePageEMSWeb.CRUDOperations.BtnUpdate.Click("101;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Employee updated successfully') on item 'HomePageEMSWeb.CRUDOperations.EmployeeUpdatedSuccessfully'.", repo.HomePageEMSWeb.CRUDOperations.EmployeeUpdatedSuccessfullyInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.HomePageEMSWeb.CRUDOperations.EmployeeUpdatedSuccessfullyInfo, "InnerText", "Employee updated successfully");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
