///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EMSTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the EMSTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ea18a46b-6a6d-4323-a010-a61e6f74838f")]
    public partial class EMSTestRepository : RepoGenBaseFolder
    {
        static EMSTestRepository instance = new EMSTestRepository();
        EMSTestRepositoryFolders.EMSMicrosoftVisualStudioAppFolder _emsmicrosoftvisualstudio;
        EMSTestRepositoryFolders.HomePageEMSWebAppFolder _homepageemsweb;

        /// <summary>
        /// Gets the singleton class instance representing the EMSTestRepository element repository.
        /// </summary>
        [RepositoryFolder("ea18a46b-6a6d-4323-a010-a61e6f74838f")]
        public static EMSTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public EMSTestRepository() 
            : base("EMSTestRepository", "/", null, 0, false, "ea18a46b-6a6d-4323-a010-a61e6f74838f", ".\\RepositoryImages\\EMSTestRepositoryea18a46b.rximgres")
        {
            _emsmicrosoftvisualstudio = new EMSTestRepositoryFolders.EMSMicrosoftVisualStudioAppFolder(this);
            _homepageemsweb = new EMSTestRepositoryFolders.HomePageEMSWebAppFolder(this);
        }

#region Variables

        string _TableIndex = "7";

        /// <summary>
        /// Gets or sets the value of variable TableIndex.
        /// </summary>
        [TestVariable("af0b8505-53fc-4375-a04c-fddcdab9fcc9")]
        public string TableIndex
        {
            get { return _TableIndex; }
            set { _TableIndex = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ea18a46b-6a6d-4323-a010-a61e6f74838f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EMSMicrosoftVisualStudio folder.
        /// </summary>
        [RepositoryFolder("7ee7912f-8cf6-4a4a-8a90-1648004593d5")]
        public virtual EMSTestRepositoryFolders.EMSMicrosoftVisualStudioAppFolder EMSMicrosoftVisualStudio
        {
            get { return _emsmicrosoftvisualstudio; }
        }

        /// <summary>
        /// The HomePageEMSWeb folder.
        /// </summary>
        [RepositoryFolder("9a1845d8-77d3-481e-933f-0a4d52a28028")]
        public virtual EMSTestRepositoryFolders.HomePageEMSWebAppFolder HomePageEMSWeb
        {
            get { return _homepageemsweb; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class EMSTestRepositoryFolders
    {
        /// <summary>
        /// The EMSMicrosoftVisualStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ee7912f-8cf6-4a4a-8a90-1648004593d5")]
        public partial class EMSMicrosoftVisualStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _launchsiteInfo;

            /// <summary>
            /// Creates a new EMSMicrosoftVisualStudio  folder.
            /// </summary>
            public EMSMicrosoftVisualStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EMSMicrosoftVisualStudio", "/form[@title>'EMS - Microsoft Visual St']", parentFolder, 30000, null, true, "7ee7912f-8cf6-4a4a-8a90-1648004593d5", "")
            {
                _launchsiteInfo = new RepoItemInfo(this, "LaunchSite", "container[@automationid='PART_ToolBarHost']/list[@automationid='PART_ToolBarFrameControlContainer']/toolbar[2]/container[@automationid='PART_ToolBarPanel']/button[16]/menubar/menuitem[@automationid='PART_FocusTarget']/button[@automationid='VsMenuControllerButton']/text[@automationid='Text']", ".//container[@automationid='PART_ToolBarPanel']/button[16]/menubar/menuitem[@automationid='PART_FocusTarget']/button[@automationid='VsMenuControllerButton']/text[@automationid='Text']", 30000, null, "4804e6ad-823a-49fd-bf28-2f8742975722");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ee7912f-8cf6-4a4a-8a90-1648004593d5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ee7912f-8cf6-4a4a-8a90-1648004593d5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LaunchSite item.
            /// </summary>
            [RepositoryItem("4804e6ad-823a-49fd-bf28-2f8742975722")]
            public virtual Ranorex.Text LaunchSite
            {
                get
                {
                    return _launchsiteInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LaunchSite item info.
            /// </summary>
            [RepositoryItemInfo("4804e6ad-823a-49fd-bf28-2f8742975722")]
            public virtual RepoItemInfo LaunchSiteInfo
            {
                get
                {
                    return _launchsiteInfo;
                }
            }
        }

        /// <summary>
        /// The HomePageEMSWebAppFolder folder.
        /// </summary>
        [RepositoryFolder("9a1845d8-77d3-481e-933f-0a4d52a28028")]
        public partial class HomePageEMSWebAppFolder : RepoGenBaseFolder
        {
            EMSTestRepositoryFolders.CRUDOperationsFolder _crudoperations;
            RepoItemInfo _welcomeInfo;
            RepoItemInfo _btnprivacyInfo;
            RepoItemInfo _privacypolicyInfo;
            RepoItemInfo _employeeInfo;
            RepoItemInfo _employeelistInfo;
            RepoItemInfo _nameInfo;
            RepoItemInfo _positionInfo;
            RepoItemInfo _salaryInfo;

            /// <summary>
            /// Creates a new HomePageEMSWeb  folder.
            /// </summary>
            public HomePageEMSWebAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePageEMSWeb", "/dom[@domain='localhost:44359']", parentFolder, 30000, null, false, "9a1845d8-77d3-481e-933f-0a4d52a28028", "")
            {
                _crudoperations = new EMSTestRepositoryFolders.CRUDOperationsFolder(this);
                _welcomeInfo = new RepoItemInfo(this, "Welcome", "body/div//h1[@innertext='Welcome']", ".//h1[@innertext='Welcome']", 30000, null, "9ae2cdba-2908-4e71-bea1-0c150ce57fc2");
                _btnprivacyInfo = new RepoItemInfo(this, "BtnPrivacy", "?/?/footer/?/?/a[@innertext='Privacy']", ".//a[@innertext='Privacy']", 30000, null, "020d41e0-333b-47c0-8564-faec39b6a88d");
                _privacypolicyInfo = new RepoItemInfo(this, "PrivacyPolicy", "body/div/?/?/h1[@innertext='Privacy Policy']", ".//h1[@innertext='Privacy Policy']", 30000, null, "3fe4ad12-a0db-45f1-ad88-4945d8983121");
                _employeeInfo = new RepoItemInfo(this, "Employee", "?/?/header/nav//ul/?/?/a[@innertext='Employee']", ".//a[@innertext='Employee']", 30000, null, "2ce29ea3-21ef-46b6-a9f5-6d6a281e69b7");
                _employeelistInfo = new RepoItemInfo(this, "EmployeeList", "body/div/main/div//h2[@innertext='Employee List']", ".//h2[@innertext='Employee List']", 30000, null, "fb525955-43ea-41f6-a4df-dc561c0e0ae3");
                _nameInfo = new RepoItemInfo(this, "Name", ".//input[#'Name']", ".//input[#'Name']", 30000, null, "05f17aa9-e949-4078-8a07-e1c2d10a373b");
                _positionInfo = new RepoItemInfo(this, "Position", ".//input[#'Position']", ".//input[#'Position']", 30000, null, "869286d1-d871-492d-9b1a-b5fcec7c8976");
                _salaryInfo = new RepoItemInfo(this, "Salary", ".//input[#'Salary']", ".//input[#'Salary']", 30000, null, "be3b40f0-2a06-4d10-8341-55013a4d75f8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9a1845d8-77d3-481e-933f-0a4d52a28028")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9a1845d8-77d3-481e-933f-0a4d52a28028")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Welcome item.
            /// </summary>
            [RepositoryItem("9ae2cdba-2908-4e71-bea1-0c150ce57fc2")]
            public virtual Ranorex.H1Tag Welcome
            {
                get
                {
                    return _welcomeInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Welcome item info.
            /// </summary>
            [RepositoryItemInfo("9ae2cdba-2908-4e71-bea1-0c150ce57fc2")]
            public virtual RepoItemInfo WelcomeInfo
            {
                get
                {
                    return _welcomeInfo;
                }
            }

            /// <summary>
            /// The BtnPrivacy item.
            /// </summary>
            [RepositoryItem("020d41e0-333b-47c0-8564-faec39b6a88d")]
            public virtual Ranorex.ATag BtnPrivacy
            {
                get
                {
                    return _btnprivacyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnPrivacy item info.
            /// </summary>
            [RepositoryItemInfo("020d41e0-333b-47c0-8564-faec39b6a88d")]
            public virtual RepoItemInfo BtnPrivacyInfo
            {
                get
                {
                    return _btnprivacyInfo;
                }
            }

            /// <summary>
            /// The PrivacyPolicy item.
            /// </summary>
            [RepositoryItem("3fe4ad12-a0db-45f1-ad88-4945d8983121")]
            public virtual Ranorex.H1Tag PrivacyPolicy
            {
                get
                {
                    return _privacypolicyInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The PrivacyPolicy item info.
            /// </summary>
            [RepositoryItemInfo("3fe4ad12-a0db-45f1-ad88-4945d8983121")]
            public virtual RepoItemInfo PrivacyPolicyInfo
            {
                get
                {
                    return _privacypolicyInfo;
                }
            }

            /// <summary>
            /// The Employee item.
            /// </summary>
            [RepositoryItem("2ce29ea3-21ef-46b6-a9f5-6d6a281e69b7")]
            public virtual Ranorex.ATag Employee
            {
                get
                {
                    return _employeeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Employee item info.
            /// </summary>
            [RepositoryItemInfo("2ce29ea3-21ef-46b6-a9f5-6d6a281e69b7")]
            public virtual RepoItemInfo EmployeeInfo
            {
                get
                {
                    return _employeeInfo;
                }
            }

            /// <summary>
            /// The EmployeeList item.
            /// </summary>
            [RepositoryItem("fb525955-43ea-41f6-a4df-dc561c0e0ae3")]
            public virtual Ranorex.H2Tag EmployeeList
            {
                get
                {
                    return _employeelistInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeeList item info.
            /// </summary>
            [RepositoryItemInfo("fb525955-43ea-41f6-a4df-dc561c0e0ae3")]
            public virtual RepoItemInfo EmployeeListInfo
            {
                get
                {
                    return _employeelistInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("05f17aa9-e949-4078-8a07-e1c2d10a373b")]
            public virtual Ranorex.InputTag Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("05f17aa9-e949-4078-8a07-e1c2d10a373b")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The Position item.
            /// </summary>
            [RepositoryItem("869286d1-d871-492d-9b1a-b5fcec7c8976")]
            public virtual Ranorex.InputTag Position
            {
                get
                {
                    return _positionInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Position item info.
            /// </summary>
            [RepositoryItemInfo("869286d1-d871-492d-9b1a-b5fcec7c8976")]
            public virtual RepoItemInfo PositionInfo
            {
                get
                {
                    return _positionInfo;
                }
            }

            /// <summary>
            /// The Salary item.
            /// </summary>
            [RepositoryItem("be3b40f0-2a06-4d10-8341-55013a4d75f8")]
            public virtual Ranorex.InputTag Salary
            {
                get
                {
                    return _salaryInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Salary item info.
            /// </summary>
            [RepositoryItemInfo("be3b40f0-2a06-4d10-8341-55013a4d75f8")]
            public virtual RepoItemInfo SalaryInfo
            {
                get
                {
                    return _salaryInfo;
                }
            }

            /// <summary>
            /// The CRUDOperations folder.
            /// </summary>
            [RepositoryFolder("a1283041-cfd1-4fde-b10c-2aba5716e18f")]
            public virtual EMSTestRepositoryFolders.CRUDOperationsFolder CRUDOperations
            {
                get { return _crudoperations; }
            }
        }

        /// <summary>
        /// The CRUDOperationsFolder folder.
        /// </summary>
        [RepositoryFolder("a1283041-cfd1-4fde-b10c-2aba5716e18f")]
        public partial class CRUDOperationsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnaddInfo;
            RepoItemInfo _employeeaddedsuccessfullyInfo;
            RepoItemInfo _btnaddnewInfo;
            RepoItemInfo _btneditInfo;
            RepoItemInfo _btnupdateInfo;
            RepoItemInfo _employeeupdatedsuccessfullyInfo;
            RepoItemInfo _btndeleteInfo;
            RepoItemInfo _btndelete1Info;
            RepoItemInfo _employeedeletedsuccessfullyInfo;
            RepoItemInfo _btnedit1Info;

            /// <summary>
            /// Creates a new CRUDOperations  folder.
            /// </summary>
            public CRUDOperationsFolder(RepoGenBaseFolder parentFolder) :
                    base("CRUDOperations", "body/div", parentFolder, 30000, null, false, "a1283041-cfd1-4fde-b10c-2aba5716e18f", "")
            {
                _btnaddInfo = new RepoItemInfo(this, "BtnAdd", "?/?/form[@action='https://localhost:44359/Employee/Create']/?/?/button[@innertext='Add']", "", 30000, null, "60ed5e84-b82d-44a9-b897-fbff8b085650");
                _employeeaddedsuccessfullyInfo = new RepoItemInfo(this, "EmployeeAddedSuccessfully", "?/?/h2[@innertext>'Employee added successful']", "", 30000, null, "09af02a2-cbdf-4ec4-84ed-c12b0413e423");
                _btnaddnewInfo = new RepoItemInfo(this, "BtnAddNew", "main/div//a[@innertext>'                Add New Employee']", "", 30000, null, "9056611e-ad53-454f-a4da-b1eca3519354");
                _btneditInfo = new RepoItemInfo(this, "BtnEdit", "?/?/table/tbody/tr[1]/td[5]/?/?/a[@innertext='Edit']", "", 30000, null, "d773df68-92ac-4996-87d3-fb30c1cd8597");
                _btnupdateInfo = new RepoItemInfo(this, "BtnUpdate", "?/?/form[@action='https://localhost:44359/Employee/Edit/6']/?/?/button[@innertext='Update']", "", 30000, null, "0663873e-0b72-4de8-bdbb-0a913dc1f817");
                _employeeupdatedsuccessfullyInfo = new RepoItemInfo(this, "EmployeeUpdatedSuccessfully", "?/?/h2[@innertext>'Employee updated successf']", "", 30000, null, "acc92e22-ee46-4041-b2af-364b435afd70");
                _btndeleteInfo = new RepoItemInfo(this, "BtnDelete", "?/?/table/tbody/tr[1]/td[5]/?/?/a[@innertext='Delete']", "", 30000, null, "41aa6424-c69a-42e9-bffc-000336b5384d");
                _btndelete1Info = new RepoItemInfo(this, "BtnDelete1", "?/?/form[@action='https://localhost:44359/Employee/DeletePOST']/?/?/button[@innertext='Delete']", "", 30000, null, "d159d27c-39ee-47ea-8235-44666fc72d72");
                _employeedeletedsuccessfullyInfo = new RepoItemInfo(this, "EmployeeDeletedSuccessfully", "?/?/h2[@innertext>'Employee deleted successf']", "", 30000, null, "5a820ea9-b8fb-4d4a-9841-1639c7f7f9ef");
                _btnedit1Info = new RepoItemInfo(this, "BtnEdit1", "?/?/table/tbody/tr[$TableIndex]/td[5]/?/?/a[@innertext='Edit']", "", 30000, null, "4dfb190a-2581-4e43-9407-eba53591c4c8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a1283041-cfd1-4fde-b10c-2aba5716e18f")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1283041-cfd1-4fde-b10c-2aba5716e18f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnAdd item.
            /// </summary>
            [RepositoryItem("60ed5e84-b82d-44a9-b897-fbff8b085650")]
            public virtual Ranorex.ButtonTag BtnAdd
            {
                get
                {
                    return _btnaddInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnAdd item info.
            /// </summary>
            [RepositoryItemInfo("60ed5e84-b82d-44a9-b897-fbff8b085650")]
            public virtual RepoItemInfo BtnAddInfo
            {
                get
                {
                    return _btnaddInfo;
                }
            }

            /// <summary>
            /// The EmployeeAddedSuccessfully item.
            /// </summary>
            [RepositoryItem("09af02a2-cbdf-4ec4-84ed-c12b0413e423")]
            public virtual Ranorex.H2Tag EmployeeAddedSuccessfully
            {
                get
                {
                    return _employeeaddedsuccessfullyInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeeAddedSuccessfully item info.
            /// </summary>
            [RepositoryItemInfo("09af02a2-cbdf-4ec4-84ed-c12b0413e423")]
            public virtual RepoItemInfo EmployeeAddedSuccessfullyInfo
            {
                get
                {
                    return _employeeaddedsuccessfullyInfo;
                }
            }

            /// <summary>
            /// The BtnAddNew item.
            /// </summary>
            [RepositoryItem("9056611e-ad53-454f-a4da-b1eca3519354")]
            public virtual Ranorex.ATag BtnAddNew
            {
                get
                {
                    return _btnaddnewInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnAddNew item info.
            /// </summary>
            [RepositoryItemInfo("9056611e-ad53-454f-a4da-b1eca3519354")]
            public virtual RepoItemInfo BtnAddNewInfo
            {
                get
                {
                    return _btnaddnewInfo;
                }
            }

            /// <summary>
            /// The BtnEdit item.
            /// </summary>
            [RepositoryItem("d773df68-92ac-4996-87d3-fb30c1cd8597")]
            public virtual Ranorex.ATag BtnEdit
            {
                get
                {
                    return _btneditInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnEdit item info.
            /// </summary>
            [RepositoryItemInfo("d773df68-92ac-4996-87d3-fb30c1cd8597")]
            public virtual RepoItemInfo BtnEditInfo
            {
                get
                {
                    return _btneditInfo;
                }
            }

            /// <summary>
            /// The BtnUpdate item.
            /// </summary>
            [RepositoryItem("0663873e-0b72-4de8-bdbb-0a913dc1f817")]
            public virtual Ranorex.ButtonTag BtnUpdate
            {
                get
                {
                    return _btnupdateInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnUpdate item info.
            /// </summary>
            [RepositoryItemInfo("0663873e-0b72-4de8-bdbb-0a913dc1f817")]
            public virtual RepoItemInfo BtnUpdateInfo
            {
                get
                {
                    return _btnupdateInfo;
                }
            }

            /// <summary>
            /// The EmployeeUpdatedSuccessfully item.
            /// </summary>
            [RepositoryItem("acc92e22-ee46-4041-b2af-364b435afd70")]
            public virtual Ranorex.H2Tag EmployeeUpdatedSuccessfully
            {
                get
                {
                    return _employeeupdatedsuccessfullyInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeeUpdatedSuccessfully item info.
            /// </summary>
            [RepositoryItemInfo("acc92e22-ee46-4041-b2af-364b435afd70")]
            public virtual RepoItemInfo EmployeeUpdatedSuccessfullyInfo
            {
                get
                {
                    return _employeeupdatedsuccessfullyInfo;
                }
            }

            /// <summary>
            /// The BtnDelete item.
            /// </summary>
            [RepositoryItem("41aa6424-c69a-42e9-bffc-000336b5384d")]
            public virtual Ranorex.ATag BtnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnDelete item info.
            /// </summary>
            [RepositoryItemInfo("41aa6424-c69a-42e9-bffc-000336b5384d")]
            public virtual RepoItemInfo BtnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }

            /// <summary>
            /// The BtnDelete1 item.
            /// </summary>
            [RepositoryItem("d159d27c-39ee-47ea-8235-44666fc72d72")]
            public virtual Ranorex.ButtonTag BtnDelete1
            {
                get
                {
                    return _btndelete1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnDelete1 item info.
            /// </summary>
            [RepositoryItemInfo("d159d27c-39ee-47ea-8235-44666fc72d72")]
            public virtual RepoItemInfo BtnDelete1Info
            {
                get
                {
                    return _btndelete1Info;
                }
            }

            /// <summary>
            /// The EmployeeDeletedSuccessfully item.
            /// </summary>
            [RepositoryItem("5a820ea9-b8fb-4d4a-9841-1639c7f7f9ef")]
            public virtual Ranorex.H2Tag EmployeeDeletedSuccessfully
            {
                get
                {
                    return _employeedeletedsuccessfullyInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The EmployeeDeletedSuccessfully item info.
            /// </summary>
            [RepositoryItemInfo("5a820ea9-b8fb-4d4a-9841-1639c7f7f9ef")]
            public virtual RepoItemInfo EmployeeDeletedSuccessfullyInfo
            {
                get
                {
                    return _employeedeletedsuccessfullyInfo;
                }
            }

            /// <summary>
            /// The BtnEdit1 item.
            /// </summary>
            [RepositoryItem("4dfb190a-2581-4e43-9407-eba53591c4c8")]
            public virtual Ranorex.ATag BtnEdit1
            {
                get
                {
                    return _btnedit1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnEdit1 item info.
            /// </summary>
            [RepositoryItemInfo("4dfb190a-2581-4e43-9407-eba53591c4c8")]
            public virtual RepoItemInfo BtnEdit1Info
            {
                get
                {
                    return _btnedit1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
